### ISSUE TITLE
THIS IS FREAKING SICK!!!!!

### ISSUE THREAD

**Issue by BlakeBrown** [chain-lib/chain-lib#7]
Seriously, developers who are new to Cardano will love this. I'd love to swap out our messy cardano-serialization-lib stuff for this as well. Any ETA on supporting datums / redeemers / SC interactions?

**Comment by wchristi0101** [comment]
Hello Blake. I am in the process of updating the repository right now to work with the newest version of CIP-30, and then I will go ahead and start supporting smart contract iterations. Im not going to give a firm eta, but perhaps ~2 months or so. We will see.
